const questions=[
{q:'Hoeveel spelers staan er per team in het veld?',a:['5', '6', '7', '8'],c:2},
{q:'Hoeveel stappen zonder stuiten?',a:['2', '3', '4', '5'],c:1},
{q:'Strafworp vanaf?',a:['6 m', '7 m', '9 m', '10 m'],c:1},
{q:'Tijdstraf duurt?',a:['1', '2', '3', '5'],c:1},
{q:'Kleur HV Novitas?',a:['Blauw', 'Groen', 'Oranje', 'Rood'],c:2},
{q:'Waar speelt HV Novitas?',a:['Hulst', 'Goes', 'Middelburg', 'Terneuzen'],c:0},
{q:'Wie verdedigt het doel?',a:['Keeper', 'Coach', 'Hoek', 'Cirkel'],c:0},
{q:'Speelduur senioren?',a:['2x20', '2x25', '2x30', '2x35'],c:2},
{q:'Aantal team time-outs?',a:['1', '2', '3', '4'],c:2},
{q:'Slogan HV Novitas?',a:['Play Hard', 'No Stress, Just Handball!', 'Orange Power', 'Handball Forever'],c:1},
{q:'Welke lijn is gestippeld?',a:['6 m', '7 m', '9 m', 'Middenlijn'],c:2},
{q:'Mag een keeper scoren?',a:['Ja', 'Nee', 'Alleen strafworp', 'Alleen laatste minuut'],c:0},
{q:'Hoeveel punten voor winst?',a:['1', '2', '3', '0'],c:1},
{q:'Welke bal gebruikt heren?',a:['Maat 1', 'Maat 2', 'Maat 3', 'Maat 4'],c:2},
{q:'Welke sport is HV Novitas?',a:['Volleybal', 'Handbal', 'Basketbal', 'Korfbal'],c:1},
];let i=0,s=0;const quiz=document.getElementById('quiz'),res=document.getElementById('result');function render(){let q=questions[i];document.getElementById('fill').style.width=(i/questions.length*100)+'%';quiz.innerHTML='<h2>Vraag '+(i+1)+' van '+questions.length+'</h2><p>'+q.q+'</p>'+q.a.map((x,n)=>`<label><input type="radio" name="r" value="${n}"> ${x}</label>`).join('');}document.getElementById('startButton').onclick=()=>{startScreen.style.display='none';game.style.display='block';render();};next.onclick=()=>{let c=document.querySelector('input[name=r]:checked');if(!c){alert('Kies een antwoord');return;}if(+c.value===questions[i].c)s++;i++;if(i<questions.length){render();}else{fill.style.width='100%';quiz.innerHTML='';let rank=s>=13?'👑 Master':s>=10?'🥇 Expert':s>=7?'🥈 Talent':'🥉 Rookie';res.innerHTML='<h2>Klaar!</h2><h1>'+s+'/'+questions.length+'</h1><h2>'+rank+'</h2>';next.style.display='none';}};
